import test from 'node:test';
import assert from 'node:assert/strict';
import {CARDS,COLORS,TOKENS,createGame,applyAction,projectGame,legalActions,evolutionActions,defaultPayment,emptyTokens,total,assertConservation} from '../web/engine.js';
import {chooseAction,AI_STYLES} from '../web/ai.js';
const rngFor=seed=>()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);
const game=(n=4)=>createGame(Array.from({length:n},(_,i)=>'Player '+i),{rng:rngFor(4)});
function extract(s,predicate){for(const d of s.decks){const i=d.findIndex(predicate);if(i>=0)return d.splice(i,1)[0];}for(const d of s.market){const i=d.findIndex(c=>c&&predicate(c));if(i>=0){const c=d[i];d[i]=null;return c;}}throw Error('fixture card missing');}
function give(s,predicate,seat=0){const c=extract(s,predicate),p=s.players[seat];p.cards.push(c);p.points+=c.points;p.bonuses[c.bonus]+=c.bonusAmount;return c;}
function supply(s,seat,tokens){for(const [c,n]of Object.entries(tokens)){s.bank[c]-=n;s.players[seat].tokens[c]+=n;}}
function show(s,predicate){const card=extract(s,predicate),row=s.market[card.tier-1];const index=row.findIndex(c=>!c);if(index>=0)row[index]=card;else{s.decks[card.tier-1].push(row[0]);row[0]=card;}return card;}
function evolutionFixture(reserved=false){const s=game();const from=give(s,c=>c.speciesId==='BULBASAUR');for(let i=0;i<3;i++)give(s,c=>c.bonus==='pink'&&c.bonusAmount===1);const to=reserved?extract(s,c=>c.speciesId==='IVYSAUR'):show(s,c=>c.speciesId==='IVYSAUR');if(reserved)s.players[0].reserved.push(to);return {s,from,to};}

test('Pokemon deck is 35/30/15/5/5 with 55 species and valid evolution links',()=>{
  assert.equal(CARDS.length,90);assert.equal(new Set(CARDS.map(c=>c.id)).size,90);assert.equal(new Set(CARDS.map(c=>c.speciesId)).size,55);
  assert.deepEqual([1,2,3,4,5].map(t=>CARDS.filter(c=>c.tier===t).length),[35,30,15,5,5]);
  for(const c of CARDS){assert.ok(Object.keys(c.cost).every(k=>TOKENS.includes(k)));if(c.evolvesToSpeciesId)assert.ok(CARDS.some(to=>to.speciesId===c.evolvesToSpeciesId&&to.stage===c.stage+1));if(c.kind!=='normal'){assert.equal(c.bonusAmount,2);assert.equal(c.cost.master,1);assert.equal(c.points,c.kind==='rare'?0:2);}}
});
for(const n of [2,3,4])test(`${n} players use correct supply, five decks and 14 face-up cards`,()=>{const s=game(n);assert.deepEqual(s.market.map(d=>d.length),[4,4,4,1,1]);assert.deepEqual(s.deckCounts,undefined);assert.equal(s.bank.master,5);assert.equal(s.bank.red,{2:4,3:5,4:7}[n]);assert.equal(s.nobles,undefined);assertConservation(s);});
test('unsupported player counts and first seats fail',()=>{assert.throws(()=>game(1));assert.throws(()=>game(5));assert.throws(()=>createGame(['A','B'],{first:2}));});
test('take validates three distinct colors and same-color threshold before removal',()=>{
  let s=game(2);assert.throws(()=>applyAction(s,0,{type:'take',colors:['red','blue']}));assert.throws(()=>applyAction(s,0,{type:'take',colors:['master']}));
  s=applyAction(s,0,{type:'take',colors:['red','red']});assert.equal(s.bank.red,2);assert.throws(()=>applyAction(s,1,{type:'take',colors:['red','red']}));assertConservation(s);
});
test('scarcity allows fewer distinct colors only when fewer remain in the supply',()=>{const s=game();s.bank={...emptyTokens(),red:1,blue:1};assert.deepEqual(legalActions(s).filter(a=>a.type==='take'),[{type:'take',colors:['red','blue']}]);assert.throws(()=>applyAction(s,0,{type:'take',colors:['red']}));});
test('wrong actor and malformed actions leave the input untouched',()=>{const s=game(),before=structuredClone(s);for(const a of [null,[],{type:'take',colors:['red','red','blue']},{type:'buy',cardId:'unknown'},{type:'pass'}])assert.throws(()=>applyAction(s,0,a));assert.throws(()=>applyAction(s,1,{type:'reserve',tier:1}));assert.deepEqual(s,before);});
test('take rejects joined color strings, empty strings and non-string colors atomically',()=>{const s=game(),before=structuredClone(s);for(const colors of [['black,blue,red'],['black,blue','red'],['black','blue','red',''],[null,'blue','red'],[{},'blue','red'],[1,'blue','red']])assert.throws(()=>applyAction(s,0,{type:'take',colors}));assert.deepEqual(s,before);assertConservation(s);});
test('normal reserve refills market, grants master ball, and stays hidden from opponents',()=>{const s=game(),card=s.market[0][0],next=s.decks[0][0];const out=applyAction(s,0,{type:'reserve',cardId:card.id});assert.equal(out.players[0].reserved[0].id,card.id);assert.equal(out.market[0][0].id,next.id);assert.equal(out.players[0].tokens.master,1);const publicView=projectGame(out,1);assert.equal(publicView.decks,undefined);assert.equal(publicView.players[0].reserved[0].id,undefined);assert.equal(publicView.players[0].reserved[0].hidden,true);assertConservation(out);});
test('blind reserve supports all three ordinary decks, never special decks',()=>{for(const tier of [1,2,3]){const s=game(),id=s.decks[tier-1][0].id;assert.equal(applyAction(s,0,{type:'reserve',tier}).players[0].reserved[0].id,id);}for(const tier of [4,5,0,8])assert.throws(()=>applyAction(game(),0,{type:'reserve',tier}));});
test('special cards cannot be reserved; lack of master balls does not block ordinary reserve',()=>{const s=game();for(const i of [3,4])assert.throws(()=>applyAction(s,0,{type:'reserve',cardId:s.market[i][0].id}));s.bank.master=0;s.players[1].tokens.master=5;const out=applyAction(s,0,{type:'reserve',tier:1});assert.equal(out.players[0].tokens.master,0);assertConservation(out);});
test('reserved hand is limited to three and cannot discard a card',()=>{let s=game();for(let i=0;i<3;i++){s.current=0;s=applyAction(s,0,{type:'reserve',tier:1});}s.current=0;assert.throws(()=>applyAction(s,0,{type:'reserve',tier:2}));assert.throws(()=>applyAction(s,0,{type:'discard',cardId:s.players[0].reserved[0].id}));});
test('over-limit reserve keeps actor until exact return, including newly acquired master ball',()=>{const s=game();supply(s,0,{red:3,blue:3,black:4});const out=applyAction(s,0,{type:'reserve',tier:1});assert.equal(out.phase,'return');assert.equal(out.current,0);assert.throws(()=>applyAction(out,0,{type:'return',tokens:{red:2}}));assert.throws(()=>applyAction(out,0,{type:'take',colors:['red','blue','pink']}));const done=applyAction(out,0,{type:'return',tokens:{master:1}});assert.equal(done.current,1);assert.equal(total(done.players[0].tokens),10);assertConservation(done);});
test('token returns reject negatives, fractional, invented colors and tokens not held',()=>{const s=game();s.phase='return';supply(s,0,{red:5,blue:5,master:1});for(const tokens of [{red:-1},{red:.5,blue:.5},{green:1},{black:1}])assert.throws(()=>applyAction(s,0,{type:'return',tokens}));});
test('capture applies permanent discounts and exact payment; master balls may replace held colors',()=>{const s=game(),card=show(s,c=>c.kind==='normal'&&c.stage===1&&c.cost.yellow===4);for(let i=0;i<2;i++)give(s,c=>c.bonus==='yellow'&&c.id!==card.id);supply(s,0,{yellow:2,master:2});const out=applyAction(s,0,{type:'buy',cardId:card.id,payment:{master:2}});assert.equal(out.players[0].tokens.yellow,2);assert.equal(out.players[0].tokens.master,0);assert.equal(out.players[0].bonuses[card.bonus],s.players[0].bonuses[card.bonus]+1);assertConservation(out);const before=structuredClone(s);for(const payment of [{yellow:3},{master:1},{yellow:1,master:2},{yellow:-1,master:3}])assert.throws(()=>applyAction(s,0,{type:'buy',cardId:card.id,payment}));assert.deepEqual(s,before);});
test('free capture and capture from own reserved hand work without awarding extra tokens',()=>{let s=game();const card=extract(s,c=>c.kind==='normal'&&c.stage===1&&c.cost.yellow===4);s.players[0].reserved.push(card);for(let i=0;i<5;i++)give(s,c=>c.bonus==='yellow'&&c.id!==card.id);const out=applyAction(s,0,{type:'buy',cardId:card.id});assert.equal(out.players[0].reserved.length,0);assert.equal(total(out.players[0].tokens),0);assertConservation(out);});
test('rare and legendary capture requires an actual master ball and gives two bonuses',()=>{for(const kind of ['rare','legendary']){const s=game(),card=show(s,c=>c.kind===kind);for(const c of COLORS)for(let i=0;i<(card.cost[c]||0);i++)give(s,x=>x.bonus===c&&x.id!==card.id);assert.throws(()=>applyAction(s,0,{type:'buy',cardId:card.id}));supply(s,0,{master:1});const out=applyAction(s,0,{type:'buy',cardId:card.id});assert.equal(out.players[0].bonuses[card.bonus],s.players[0].bonuses[card.bonus]+2);assert.equal(out.players[0].tokens.master,0);assertConservation(out);}});
test('evolution checks bonuses, never spendable tokens',()=>{const {s,from,to}=evolutionFixture();s.players[0].bonuses.pink=0;s.players[0].tokens.pink=3;assert.equal(evolutionActions(s).some(a=>a.fromId===from.id&&a.cardId===to.id),false);});
for(const reserved of [false,true])test(`evolution can use ${reserved?'reserved':'market'} next stage, replaces old score/bonus and happens only once`,()=>{const {s,from,to}=evolutionFixture(reserved);const before=s.players[0].points;const step=applyAction(s,0,{type:'take',colors:['red','blue','yellow']});assert.equal(step.phase,'evolve');assert.equal(step.current,0);const out=applyAction(step,0,{type:'evolve',fromId:from.id,cardId:to.id});assert.equal(out.players[0].points,before-from.points+to.points);assert.equal(out.players[0].evolved[0].id,from.id);assert.ok(!out.players[0].cards.some(c=>c.id===from.id));assert.equal(out.current,1);assert.equal(projectGame(out,1).players[0].evolved[0].id,undefined);assert.throws(()=>applyAction(out,0,{type:'evolve',fromId:from.id,cardId:to.id}));assertConservation(out);});
test('evolution is optional and cannot skip directly from stage 1 to stage 3',()=>{const {s,from}=evolutionFixture(),third=show(s,c=>c.speciesId==='VENUSAUR');s.phase='evolve';assert.throws(()=>applyAction(s,0,{type:'evolve',fromId:from.id,cardId:third.id}));const out=applyAction(s,0,{type:'finish'});assert.equal(out.players[0].evolved.length,0);assert.equal(out.current,1);});
test('return phase precedes evolution and final-round trigger',()=>{const {s}=evolutionFixture();supply(s,0,{red:5,blue:5});s.players[0].points=18;const step=applyAction(s,0,{type:'reserve',tier:1});assert.equal(step.phase,'return');assert.equal(step.finalRound,false);const evo=applyAction(step,0,{type:'return',tokens:{master:1}});assert.equal(evo.phase,'evolve');assert.equal(evo.finalRound,false);const finished=applyAction(evo,0,{type:'finish'});assert.equal(finished.finalRound,true);});
test('18 points completes the round relative to a nonzero first player',()=>{let s=game();s.first=2;s.current=2;s.players[2].points=18;s.phase='evolve';s=applyAction(s,2,{type:'finish'});assert.equal(s.phase,'action');assert.equal(s.current,3);for(const seat of [3,0,1]){s.phase='evolve';s=applyAction(s,seat,{type:'finish'});}assert.equal(s.phase,'complete');assert.deepEqual(s.winners,[2]);assert.throws(()=>applyAction(s,2,{type:'take',colors:['red','blue','pink']}));});
test('tie breaks by MORE evolutions then MORE active cards, then shared victory',()=>{for(const [evolved,cards,winners]of [[[2,1],[1,5],[0]],[[2,2],[1,5],[1]],[[2,2],[5,5],[0,1]]]){let s=game(2);s.current=1;s.phase='evolve';s.players.forEach((p,i)=>{p.points=18;p.evolved=Array(evolved[i]).fill({});p.cards=Array(cards[i]).fill({});});s=applyAction(s,1,{type:'finish'});assert.deepEqual(s.winners,winners);}});
test('exhausted decks leave empty slots; blind reserve is not available',()=>{const s=game();s.decks[0]=[];const id=s.market[0][0].id;const out=applyAction(s,0,{type:'reserve',cardId:id});assert.equal(out.market[0][0],null);assert.ok(!legalActions(out).some(a=>a.type==='reserve'&&a.tier===1));});
test('pass exists only when all main actions are impossible',()=>{const s=game();s.bank=emptyTokens();s.market=s.market.map(row=>row.map(()=>null));s.decks=s.decks.map(()=>[]);assert.deepEqual(legalActions(s),[{type:'pass'}]);assert.equal(applyAction(s,0,{type:'pass'}).current,1);});
test('AI completes 36 seeded 2/3/4-player games with conservation after every decision',()=>{for(const n of [2,3,4])for(let seed=1;seed<=12;seed++){let s=createGame(Array.from({length:n},(_,i)=>'AI '+i),{rng:rngFor(seed),first:seed%n}),moves=0;while(s.phase!=='complete'&&moves<350){const seat=s.current;const v=projectGame(s,seat);assert.equal(v.decks,undefined);s=applyAction(s,seat,chooseAction(v,AI_STYLES[seat%3].id));assertConservation(s);moves++;}assert.equal(s.phase,'complete',`${n} players / seed ${seed}`);assert.ok(s.players.some(p=>p.points>=18));}});
