import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes,randomUUID} from 'node:crypto';
import {createTabletopServer} from '../../../server/index.mjs';
import worker from '../../../deploy/cloudflare/worker.mjs';
const key=()=>randomBytes(24).toString('hex');
async function start(dataDir){const app=await createTabletopServer({dataDir});await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));return {...app,url:'http://127.0.0.1:'+app.server.address().port};}
async function call(app,path,{body,token,origin}={}){const r=await fetch(app.url+path,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{}),...(origin?{Origin:origin}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,headers:r.headers,data:await r.json()};}
test('collection routes all Pokemon assets while keeping server, licenses and room data private',async t=>{const dir=await mkdtemp(join(tmpdir(),'pokemon-http-')),app=await start(dir);t.after(async()=>{await app.close();await rm(dir,{recursive:true,force:true});});const catalog=await call(app,'/games.json');assert.equal(catalog.data.length,3);assert.equal(catalog.data[1].id,'splendor');for(const path of ['/games/splendor/index.html','/games/splendor/online.html','/games/splendor/engine.js','/games/splendor/data.js','/games/splendor/ai.js','/games/splendor/human-avatars.js','/games/splendor/assets/players/human-star.webp','/games/splendor/style.css','/games/splendor/ui.js','/games/splendor/feedback.js','/games/splendor/feedback-events.js','/games/splendor/feedback.css','/games/splendor/artwork.js','/games/splendor/assets/pokemon/008-wartortle.svg','/games/splendor/','/games/texas-holdem/index.html'])assert.equal((await fetch(app.url+path)).status,200,path);for(const path of ['/games/splendor/server/rooms.mjs','/.data/splendor-rooms.json','/games/splendor/%2f..%2fserver%2frooms.mjs','/games/splendor/licenses/Pokemon-reference.txt'])assert.equal((await fetch(app.url+path)).status,404,path);});
test('real HTTP identity, two-player actions, retries and server-restart persistence',async t=>{const dir=await mkdtemp(join(tmpdir(),'pokemon-room-'));let app=await start(dir);t.after(async()=>{await app.close();await rm(dir,{recursive:true,force:true});});const {data:host,status}=await call(app,'/api/splendor/rooms',{body:{name:'Host',capacity:2,seatKey:key()}});assert.equal(status,201);const path='/api/splendor/rooms/'+host.room.code;const {data:guest}=await call(app,path+'/join',{body:{name:'Guest',seatKey:key()}});const {data:ready}=await call(app,path+'/ready',{token:guest.token,body:{ready:true,version:guest.room.version,requestId:randomUUID()}});const {data:started}=await call(app,path+'/start',{token:host.token,body:{version:ready.room.version,requestId:randomUUID()}});const token=[host.token,guest.token][started.game.current],seat=started.game.current,body={version:started.room.version,requestId:randomUUID(),action:{type:'reserve',tier:1}};const {data:moved}=await call(app,path+'/action',{token,body});const {data:retry}=await call(app,path+'/action',{token,body});assert.equal(retry.game.version,moved.game.version);assert.equal((await call(app,path)).status,403);assert.equal((await call(app,path,{token,origin:'https://evil.example'})).status,403);const other=[host.token,guest.token][1-seat];const privateView=await call(app,path,{token:other});assert.equal(privateView.data.game.players[seat].reserved[0].hidden,true);assert.match(privateView.headers.get('cache-control'),/no-store/);const disk=await readFile(join(dir,'splendor-rooms.json'),'utf8');assert.ok(!disk.includes(host.token));assert.ok(!disk.includes(guest.token));await app.close();app=await start(dir);const restored=await call(app,path,{token});assert.deepEqual(restored.data.game.players[seat].reserved,moved.game.players[seat].reserved);assert.equal(restored.data.game.version,moved.game.version);});
test('HTTP rejects oversized bodies and missing content types, and Cloudflare reports missing Pokemon storage honestly',async t=>{const dir=await mkdtemp(join(tmpdir(),'pokemon-input-')),app=await start(dir);t.after(async()=>{await app.close();await rm(dir,{recursive:true,force:true});});assert.equal((await fetch(app.url+'/api/splendor/rooms',{method:'POST',body:'{}'})).status,415);assert.equal((await fetch(app.url+'/api/splendor/rooms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'x'.repeat(9000)})})).status,413);const r=await worker.fetch(new Request('https://example.com/api/splendor/health'),{});assert.equal(r.status,503);assert.match((await r.json()).error,/配置/);});
