import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir,mkdtemp} from 'node:fs/promises';
import {createTabletopServer} from '../server/index.mjs';
const require=createRequire(process.env.PLAYWRIGHT_MODULE_PATH||import.meta.url);
const {chromium}=require('playwright');
await mkdir('_qa/ink-war',{recursive:true});
const app=await createTabletopServer({dataDir:await mkdtemp('_qa/ink-war/data-')});
await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));
const base=`http://127.0.0.1:${app.server.address().port}`;
let browser;
const errors=[];
function onErrors(page){page.on('pageerror',error=>errors.push(error.message));}
async function observeBattle(page){await page.evaluate(async()=>{const {BattlefieldRenderer}=await import('./renderer.js'),receive=BattlefieldRenderer.prototype.receive;BattlefieldRenderer.prototype.receive=function(...args){if(!this.preview)window.__inkBattle=this;return receive.apply(this,args);};});}
async function clickWorld(page,state,target){
  const cameraPoint=await page.evaluate(target=>window.__inkBattle?.point(target.x,target.y),target);
  if(cameraPoint){const box=await page.locator('#board').boundingBox();await page.mouse.click(box.x+cameraPoint.x,box.y+cameraPoint.y);return;}
  const box=await page.locator('#board').boundingBox(),portrait=box.height>box.width*1.12;
  const ww=portrait?state.height:state.width,hh=portrait?state.width:state.height,top=Math.min(140,Math.max(80,box.height*.17));
  const scale=Math.min((box.width-24)/ww,(box.height-top-12)/hh);
  const x=(portrait?target.y:target.x)*scale+(box.width-ww*scale)/2;
  const y=(portrait?state.width-target.x:target.y)*scale+top+(box.height-top-12-hh*scale)/2;
  await page.mouse.click(box.x+x,box.y+y);
}
async function operation(page,op,click){const promise=page.waitForResponse(r=>r.url().endsWith('/'+op)&&r.request().method()==='POST');await click();const response=await promise;const data=await response.json();assert.equal(response.status(),op==='rooms'?201:200,`${op}: ${data.error||'ok'}`);return data;}
try{
  browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||'msedge',headless:true});
  const contextA=await browser.newContext({viewport:{width:1440,height:1000}}),contextB=await browser.newContext({viewport:{width:1280,height:900}});
  const a=await contextA.newPage(),b=await contextB.newPage();onErrors(a);onErrors(b);
  await a.goto(base+'/games/ink-war/index.html');await a.locator('#solo-cards .card-option').first().waitFor();
  await a.evaluate(()=>{const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(...args){if(this.src.includes('ink-battle.wav'))window.__inkMusic=this;return play.apply(this,args);};});
  await a.locator('#music-button').click();assert.equal(await a.locator('#music-button').textContent(),'音乐：关');
  await a.locator('#music-button').click();await a.waitForFunction(()=>window.__inkMusic?.readyState>=2&&!window.__inkMusic.paused);
  assert.ok(await a.evaluate(()=>window.__inkMusic.loop&&window.__inkMusic.duration===48));
  assert.equal(await a.locator('#solo-count').inputValue(),'3');assert.equal(await a.locator('#solo-difficulty').inputValue(),'beginner');
  await observeBattle(a);
  await a.evaluate(()=>document.fonts.load('24px InkBrush'));await a.waitForTimeout(150);
  assert.equal(await a.locator('#solo-cards .card-option').count(),3);
  await a.screenshot({path:'_qa/ink-war/desktop-home.png',fullPage:true});
  await a.locator('#preview').screenshot({path:'_qa/ink-war/seven-kingdoms.png'});
  await a.locator('#solo-count').selectOption('4');await a.locator('#solo-map').selectOption('passes');
  await a.locator('#solo-start').click();await a.locator('#battle').waitFor({state:'visible'});
  await a.locator('#pause-button').click();
  assert.ok(await a.evaluate(()=>window.__inkMusic.paused),'pausing a solo battle pauses music');
  assert.equal(await a.locator('#factions .faction').count(),4);
  assert.equal(await a.locator('#army-total').textContent(),'战场兵力 0','new solo battles start with no soldiers');
  const firstMap=await a.evaluate(()=>({seed:window.__inkBattle.state.seed,width:window.__inkBattle.state.width,height:window.__inkBattle.state.height,cities:window.__inkBattle.state.cities.map(c=>[c.x,c.y])}));
  assert.equal(await a.evaluate(()=>window.__inkBattle.state.aiDifficulty),'beginner');assert.match(await a.locator('#battle-mode').textContent(),/入门/);
  assert.equal(firstMap.cities.length,16,'four-country battles spread over sixteen cities');
  await a.locator('#select-all').click();assert.equal(await a.locator('#selection-indicator').textContent(),'划选士兵 · 点击位置出征');
  await a.locator('#resume-button').click();
  await a.waitForFunction(()=>Number(document.querySelector('#factions .self .count:last-child').textContent.match(/\d+/)?.[0]||0)>0);
  await a.evaluate(()=>{const u=window.__inkBattle.state.units.find(u=>u.owner===0&&Number.isInteger(u.garrisonSlot));window.__patrolProbe={id:u.id,x:u.x,y:u.y};});
  await a.waitForFunction(()=>{const p=window.__patrolProbe,u=window.__inkBattle.state.units.find(u=>u.id===p.id);return u&&Math.hypot(u.x-p.x,u.y-p.y)>5;});
  await a.locator('#select-all').click();assert.match(await a.locator('#selection-indicator').textContent(),/已选 \d+ 名士兵/);
  await a.waitForFunction(()=>document.querySelector('#battle-time').textContent!=='00:00');
  await a.locator('#pause-button').click();const clock=await a.locator('#battle-time').textContent();await a.waitForTimeout(1150);assert.equal(await a.locator('#battle-time').textContent(),clock);
  await a.locator('#resume-button').click();
  await a.locator('#zoom-in').click();assert.ok(await a.evaluate(()=>window.__inkBattle.zoom)>1);
  const cameraBefore=await a.evaluate(()=>({left:window.__inkBattle.view.left,top:window.__inkBattle.view.top}));
  await a.locator('#pan-map').click();const dragBox=await a.locator('#board').boundingBox();await a.mouse.move(dragBox.x+dragBox.width/2,dragBox.y+dragBox.height/2);await a.mouse.down();await a.mouse.move(dragBox.x+dragBox.width/2+25,dragBox.y+dragBox.height/2+45,{steps:5});await a.mouse.up();
  const cameraAfter=await a.evaluate(()=>({left:window.__inkBattle.view.left,top:window.__inkBattle.view.top}));assert.notDeepEqual(cameraAfter,cameraBefore,'pan mode moves the enlarged map');
  await a.locator('#pan-map').click();await a.locator('#map-fit').click();assert.equal(await a.evaluate(()=>window.__inkBattle.zoom),1);
  await a.locator('#home-city').click();assert.equal(await a.evaluate(()=>window.__inkBattle.zoom),2);await a.locator('#map-fit').click();
  await a.screenshot({path:'_qa/ink-war/desktop-battle.png',fullPage:true});
  await a.locator('#pause-button').click();
  const feedCity=await a.evaluate(()=>{const renderer=window.__inkBattle,state=renderer.state,city=state.cities.find(c=>c.owner===0),template=state.units.find(u=>u.owner===0);city.level=1;city.maxLevel=3;city.upgradeUnits=0;city.radius=32;city.hp=city.maxHp-20;state.units=state.units.filter(u=>u.owner!==0);const ids=[];for(let i=0;i<43;i++){const unit={...template,id:state.nextUnitId++,x:city.x,y:city.y,target:null};delete unit.garrisonCityId;delete unit.garrisonSlot;delete unit.cityOrder;state.units.push(unit);ids.push(unit.id);}renderer.receive(state,{interval:100});return {id:city.id,x:city.x,y:city.y,maxHp:city.maxHp,ids};});
  await a.locator('#select-all').click();await a.locator('#resume-button').click();await clickWorld(a,firstMap,feedCity);
  await a.waitForFunction(id=>window.__inkBattle.state.cities.find(c=>c.id===id).level===3,feedCity.id);
  await a.locator('#pause-button').click();
  const upgraded=await a.evaluate(({id,ids})=>{const state=window.__inkBattle.state,city=state.cities.find(c=>c.id===id);return {city,survivors:state.units.filter(u=>ids.includes(u.id)).length};},feedCity);
  assert.equal(upgraded.city.upgradeUnits,40);assert.equal(upgraded.city.radius,44);assert.ok(upgraded.city.maxHp>feedCity.maxHp);assert.equal(upgraded.city.hp,upgraded.city.maxHp);assert.equal(upgraded.survivors,2,'one heals, forty upgrade, two survive a full level-three city');
  assert.equal(await a.locator('#city-status').count(),0,'city name and level status row is removed');
  await a.waitForTimeout(550);
  const cityDrawing=await a.evaluate(id=>{const renderer=window.__inkBattle,city=renderer.state.cities.find(c=>c.id===id),text=[],ctx=renderer.ctx,fillText=ctx.fillText;ctx.fillText=function(value,...args){text.push(value);return fillText.call(this,value,...args);};try{renderer.draw(renderer.state,performance.now());}finally{ctx.fillText=fillText;}return {ringCounts:[1,2,3].map(maxLevel=>renderer.cityGrowthRings({maxLevel}).length),ringTargets:renderer.cityGrowthRings(city),inkRadius:renderer.citySize(city)*.44,names:renderer.state.cities.map(c=>c.name),text};},feedCity.id);
  assert.deepEqual(cityDrawing.ringCounts,[0,1,2],'level ceilings have zero, one, and two fixed target outlines');
  assert.ok(Math.abs(cityDrawing.inkRadius-cityDrawing.ringTargets.at(-1))<0.01,'the full level-three ink edge reaches its outer target outline');
  assert.ok(cityDrawing.text.every(text=>!text.includes('级')&&!text.includes('驻军')&&!cityDrawing.names.some(name=>text.includes(name))),'the map has no city names, level numbers or garrison captions');
  await a.locator('#resume-button').click();await a.locator('#zoom-in').click();await a.locator('#home-city').click();
  await a.screenshot({path:'_qa/ink-war/city-levels.png',fullPage:true});
  await a.evaluate(async()=>{const {releaseComebackSkill}=await import('./engine.js');releaseComebackSkill(window.__inkBattle.state,0,'rush');window.__inkBattle.receive(window.__inkBattle.state,{interval:100});});
  await a.waitForFunction(()=>document.querySelector('#battle-notice').textContent.includes('急行军'));
  await a.locator('#select-all').click();
  assert.ok(await a.evaluate(()=>{const r=window.__inkBattle;return r.state.units.some(u=>u.uncontrollable)&&r.state.units.filter(u=>u.uncontrollable).every(u=>!r.selection.has(u.id));}),'automatic assault troops cannot be selected by the all-army button');
  await a.screenshot({path:'_qa/ink-war/counterattack.png',fullPage:true});
  await a.evaluate(async()=>{const {stepGame}=await import('./engine.js'),r=window.__inkBattle;r.state.players[0].comeback.losses.push(r.state.time);stepGame(r.state);r.receive(r.state,{interval:100});});
  await a.waitForFunction(()=>document.querySelector('#battle-notice').textContent.includes('神凌'));
  assert.ok(await a.evaluate(()=>window.__inkBattle.state.units.filter(u=>u.owner===0&&!u.uncontrollable).length>=200));
  assert.ok(await a.evaluate(()=>window.__inkBattle.effects.some(e=>e.divine)));
  await a.screenshot({path:'_qa/ink-war/divine-rescue.png',fullPage:true});
  await a.locator('#battle-exit').click();
  await a.locator('#solo-start').click();await a.locator('#battle').waitFor({state:'visible'});
  const secondMap=await a.evaluate(()=>({seed:window.__inkBattle.state.seed,cities:window.__inkBattle.state.cities.map(c=>[c.x,c.y])}));assert.notEqual(secondMap.seed,firstMap.seed);assert.notDeepEqual(secondMap.cities,firstMap.cities,'new solo battles regenerate the full layout');await a.locator('#battle-exit').click();
  await a.locator('#online-tab').click();await a.locator('#nickname').fill('青墨城主');
  const created=await operation(a,'rooms',()=>a.locator('#create-room').click());
  await a.locator('#lobby').waitFor({state:'visible'});
  assert.equal(await a.locator('#room-start').isDisabled(),true,'empty seats cannot start');
  await b.goto(base+'/games/ink-war/online.html?room='+created.room.code);await b.locator('#online-form').waitFor({state:'visible'});
  await observeBattle(b);
  assert.equal(await b.locator('#room-code').inputValue(),created.room.code);
  await b.locator('#nickname').fill('朱砂城主');
  const joinPath=base+'/api/ink-war/rooms/'+created.room.code+'/join';
  await b.route(joinPath,async route=>{const response=await route.fetch();assert.equal(response.status(),200);await route.fulfill({status:503,json:{error:'模拟响应丢失，请重试。'}});});
  await b.locator('#join-room').click();await b.locator('#home-error').waitFor({state:'visible'});await b.unroute(joinPath);
  const joined=await operation(b,'join',()=>b.locator('#join-room').click());
  assert.equal(joined.room.selfSeat,1,'retry recovers the committed seat after a lost join response');
  await operation(a,'ready',()=>a.locator('#ready-button').click());await operation(b,'ready',()=>b.locator('#ready-button').click());
  await a.waitForFunction(()=>!document.querySelector('#room-start').disabled);
  await a.screenshot({path:'_qa/ink-war/friend-lobby.png',fullPage:true});
  const started=await operation(a,'start',()=>a.locator('#room-start').click());
  assert.equal(started.game.units.length,0,'new online battles start with no soldiers');
  assert.ok(started.game.players.every(p=>p.alive),'empty armies still own their live capitals');
  await a.locator('#battle').waitFor({state:'visible'});await b.locator('#battle').waitFor({state:'visible'});
  assert.equal(await a.locator('#pause-button').isVisible(),false);
  await Promise.all([a,b].map(page=>page.waitForFunction(()=>document.querySelector('#factions .self .count:last-child').textContent.match(/\d+/)?.[0]!=='0')));
  const [targetA,targetB]=await Promise.all([a,b].map((page,owner)=>page.evaluate(owner=>{const state=window.__inkBattle.state,u=state.units.find(u=>u.owner===owner),home=state.cities.find(c=>c.owner===owner),dx=u.x-home.x,dy=u.y-home.y,length=Math.hypot(dx,dy);return {x:Math.max(12,Math.min(state.width-12,u.x+dx/length*90)),y:Math.max(12,Math.min(state.height-12,u.y+dy/length*90))};},owner)));
  await a.locator('#select-all').click();await b.locator('#select-all').click();
  const [orderedA,orderedB]=await Promise.all([
    operation(a,'action',()=>clickWorld(a,started.game,targetA)),
    operation(b,'action',()=>clickWorld(b,started.game,targetB)),
  ]);
  assert.ok(orderedA.game.units.some(u=>u.owner===0&&u.target),'host order accepted');
  assert.ok(orderedB.game.units.some(u=>u.owner===1&&u.target),'guest order accepted');
  await a.waitForTimeout(1400);
  const snapshot=await a.request.get(base+'/api/ink-war/rooms/'+created.room.code,{headers:{Authorization:'Bearer '+created.token}});
  const live=await snapshot.json();for(const [data,owner] of [[orderedA,0],[orderedB,1]]){const original=data.game.units.find(u=>u.owner===owner&&u.target),moved=live.game.units.find(u=>u.id===original.id);assert.ok(moved&&Math.hypot(moved.x-original.target.x,moved.y-original.target.y)<Math.hypot(original.x-original.target.x,original.y-original.target.y),'each newly produced army moves toward its order');}
  await a.screenshot({path:'_qa/ink-war/friend-battle.png',fullPage:true});
  await b.reload();await b.locator('#battle').waitFor({state:'visible'});assert.match(await b.locator('#factions .self .faction-name').textContent(),/朱砂城主/);
  let releasePoll,markCaptured;
  const delayedPoll=new Promise(resolve=>releasePoll=resolve),capturedPoll=new Promise(resolve=>markCaptured=resolve);
  const roomPath=base+'/api/ink-war/rooms/'+created.room.code;
  await b.route(roomPath,async route=>{const response=await route.fetch();markCaptured();await delayedPoll;await route.fulfill({response});});
  await capturedPoll;
  b.once('dialog',dialog=>dialog.accept());
  await operation(b,'leave',()=>b.locator('#battle-exit').click());
  releasePoll();await b.waitForTimeout(500);await b.unroute(roomPath);
  assert.equal(await b.locator('#home').isVisible(),true,'a delayed old poll cannot restore the surrendered room');
  await a.locator('#result-dialog').waitFor({state:'visible'});
  assert.equal(await a.locator('#result-glyph').textContent(),'胜');
  await operation(a,'rematch',()=>a.locator('#play-again').click());await a.locator('#lobby').waitFor({state:'visible'});
  const beforeReady=await a.locator('#lobby-cards .card-option.selected').getAttribute('data-card');
  await operation(a,'ready',()=>a.locator('#ready-button').click());
  assert.equal(await a.locator('#room-start').isDisabled(),true,'departed player cannot be silently replaced');
  assert.ok(beforeReady);
  const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const m=await mobile.newPage();onErrors(m);
  await m.goto(base+'/games/ink-war/index.html');await m.locator('#solo-cards .card-option').first().waitFor();await m.evaluate(()=>document.fonts.load('24px InkBrush'));await m.waitForTimeout(150);
  await observeBattle(m);
  assert.ok(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile home has no horizontal overflow');
  await m.screenshot({path:'_qa/ink-war/mobile-home.png',fullPage:true});
  await m.locator('#solo-count').selectOption('7');
  await m.locator('#solo-start').tap();await m.locator('#battle').waitFor({state:'visible'});await m.waitForFunction(()=>Number(document.querySelector('#factions .self .count:last-child').textContent.match(/\d+/)?.[0]||0)>0);await m.locator('#select-all').tap();assert.match(await m.locator('#selection-indicator').textContent(),/已选/);
  assert.equal(await m.locator('#factions .faction').count(),7);
  const mobileMap=await m.evaluate(()=>({width:window.__inkBattle.state.width,height:window.__inkBattle.state.height,cities:window.__inkBattle.state.cities.length}));assert.equal(mobileMap.cities,28);assert.ok(mobileMap.width>firstMap.width&&mobileMap.height>firstMap.height);
  await m.locator('#zoom-in').tap();assert.ok(await m.evaluate(()=>window.__inkBattle.zoom)>1);await m.locator('#map-fit').tap();
  assert.ok(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile battlefield has no horizontal overflow');
  await m.screenshot({path:'_qa/ink-war/mobile-battle.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('Ink War browser checks passed: solo selection/pause, city click feeding/healing/two level breakthroughs/max-level survivors, independent two-player join/ready/start/simultaneous orders, lost-response retry, refresh recovery, surrender/rematch, delayed poll isolation, mobile layout. Screenshots: _qa/ink-war/');
}finally{await browser?.close();await app.close();}
